### ISSUE TITLE
Need extra "action"column when selecting tracks, playlists, releases

### ISSUE THREAD

**Issue by zuratama** [paradigm258/Indie-Vibe-Back#17]
Khi select ra tracks, playlists, releases cho người dùng để hiển thị, tôi muốn có thêm trường "action" để thể hiện quan hệ giữa User gửi request lên với tracks, playlists, releases được request.

Hiện tại mấy cái DTO simple chưa có trường "action", nếu mình demo select được thêm trường "action" cho 1 cái, mình sẽ bổ sung thêm.

**Comment by paradigm258** [comment]
added relation property to DTOs
