### ISSUE TITLE
Type mismatch error when thumbnail is null (not provided)

### ISSUE THREAD

**Issue by zuratama** [paradigm258/Indie-Vibe-Back#28]
https://github.com/paradigm258/Indie-Vibe-Back/blob/aebfe4c5c722a6c0ec2e5edac230863650b3e19e/src/main/java/com/swp493/ivb/common/playlist/ControllerPlaylist.java#L37

Tạo playlist không có thumbnail, thumbnail = null bị ra lỗi type mismatch ô ơi.

**Comment by paradigm258** [comment]
thumbnail field need its type to be set as file in post request
